Parameters:
  oiuip:
    Type: String
    Description: The name of the S3 bucket
  Environment:
    Description: This stack's environment.
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod

Resources:
  ExampleBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref oiuip
      Tags:
        - Key: Env
          Value: !Join [ '-', [ !Ref Environment, environment ] ]